// Code generated by Prisma (prisma@1.34.10). DO NOT EDIT.
  // Please don't change this file manually but run `prisma generate` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

export const typeDefs = /* GraphQL */ `type AggregatePunbbBan {
  count: Int!
}

type AggregatePunbbCategory {
  count: Int!
}

type AggregatePunbbForum {
  count: Int!
}

type AggregatePunbbOnline {
  count: Int!
}

type AggregatePunbbPost {
  count: Int!
}

type AggregatePunbbTopic {
  count: Int!
}

type AggregatePunbbUploaded {
  count: Int!
}

type AggregatePunbbUser {
  count: Int!
}

type BatchPayload {
  count: Long!
}

scalar Long

type Mutation {
  createPunbbBan(data: PunbbBanCreateInput!): PunbbBan!
  updatePunbbBan(data: PunbbBanUpdateInput!, where: PunbbBanWhereUniqueInput!): PunbbBan
  updateManyPunbbBans(data: PunbbBanUpdateManyMutationInput!, where: PunbbBanWhereInput): BatchPayload!
  upsertPunbbBan(where: PunbbBanWhereUniqueInput!, create: PunbbBanCreateInput!, update: PunbbBanUpdateInput!): PunbbBan!
  deletePunbbBan(where: PunbbBanWhereUniqueInput!): PunbbBan
  deleteManyPunbbBans(where: PunbbBanWhereInput): BatchPayload!
  createPunbbCategory(data: PunbbCategoryCreateInput!): PunbbCategory!
  updatePunbbCategory(data: PunbbCategoryUpdateInput!, where: PunbbCategoryWhereUniqueInput!): PunbbCategory
  updateManyPunbbCategories(data: PunbbCategoryUpdateManyMutationInput!, where: PunbbCategoryWhereInput): BatchPayload!
  upsertPunbbCategory(where: PunbbCategoryWhereUniqueInput!, create: PunbbCategoryCreateInput!, update: PunbbCategoryUpdateInput!): PunbbCategory!
  deletePunbbCategory(where: PunbbCategoryWhereUniqueInput!): PunbbCategory
  deleteManyPunbbCategories(where: PunbbCategoryWhereInput): BatchPayload!
  createPunbbForum(data: PunbbForumCreateInput!): PunbbForum!
  updatePunbbForum(data: PunbbForumUpdateInput!, where: PunbbForumWhereUniqueInput!): PunbbForum
  updateManyPunbbForums(data: PunbbForumUpdateManyMutationInput!, where: PunbbForumWhereInput): BatchPayload!
  upsertPunbbForum(where: PunbbForumWhereUniqueInput!, create: PunbbForumCreateInput!, update: PunbbForumUpdateInput!): PunbbForum!
  deletePunbbForum(where: PunbbForumWhereUniqueInput!): PunbbForum
  deleteManyPunbbForums(where: PunbbForumWhereInput): BatchPayload!
  createPunbbOnline(data: PunbbOnlineCreateInput!): PunbbOnline!
  updatePunbbOnline(data: PunbbOnlineUpdateInput!, where: PunbbOnlineWhereUniqueInput!): PunbbOnline
  updateManyPunbbOnlines(data: PunbbOnlineUpdateManyMutationInput!, where: PunbbOnlineWhereInput): BatchPayload!
  upsertPunbbOnline(where: PunbbOnlineWhereUniqueInput!, create: PunbbOnlineCreateInput!, update: PunbbOnlineUpdateInput!): PunbbOnline!
  deletePunbbOnline(where: PunbbOnlineWhereUniqueInput!): PunbbOnline
  deleteManyPunbbOnlines(where: PunbbOnlineWhereInput): BatchPayload!
  createPunbbPost(data: PunbbPostCreateInput!): PunbbPost!
  updatePunbbPost(data: PunbbPostUpdateInput!, where: PunbbPostWhereUniqueInput!): PunbbPost
  updateManyPunbbPosts(data: PunbbPostUpdateManyMutationInput!, where: PunbbPostWhereInput): BatchPayload!
  upsertPunbbPost(where: PunbbPostWhereUniqueInput!, create: PunbbPostCreateInput!, update: PunbbPostUpdateInput!): PunbbPost!
  deletePunbbPost(where: PunbbPostWhereUniqueInput!): PunbbPost
  deleteManyPunbbPosts(where: PunbbPostWhereInput): BatchPayload!
  createPunbbTopic(data: PunbbTopicCreateInput!): PunbbTopic!
  updatePunbbTopic(data: PunbbTopicUpdateInput!, where: PunbbTopicWhereUniqueInput!): PunbbTopic
  updateManyPunbbTopics(data: PunbbTopicUpdateManyMutationInput!, where: PunbbTopicWhereInput): BatchPayload!
  upsertPunbbTopic(where: PunbbTopicWhereUniqueInput!, create: PunbbTopicCreateInput!, update: PunbbTopicUpdateInput!): PunbbTopic!
  deletePunbbTopic(where: PunbbTopicWhereUniqueInput!): PunbbTopic
  deleteManyPunbbTopics(where: PunbbTopicWhereInput): BatchPayload!
  createPunbbUploaded(data: PunbbUploadedCreateInput!): PunbbUploaded!
  updatePunbbUploaded(data: PunbbUploadedUpdateInput!, where: PunbbUploadedWhereUniqueInput!): PunbbUploaded
  updateManyPunbbUploadeds(data: PunbbUploadedUpdateManyMutationInput!, where: PunbbUploadedWhereInput): BatchPayload!
  upsertPunbbUploaded(where: PunbbUploadedWhereUniqueInput!, create: PunbbUploadedCreateInput!, update: PunbbUploadedUpdateInput!): PunbbUploaded!
  deletePunbbUploaded(where: PunbbUploadedWhereUniqueInput!): PunbbUploaded
  deleteManyPunbbUploadeds(where: PunbbUploadedWhereInput): BatchPayload!
  createPunbbUser(data: PunbbUserCreateInput!): PunbbUser!
  updatePunbbUser(data: PunbbUserUpdateInput!, where: PunbbUserWhereUniqueInput!): PunbbUser
  updateManyPunbbUsers(data: PunbbUserUpdateManyMutationInput!, where: PunbbUserWhereInput): BatchPayload!
  upsertPunbbUser(where: PunbbUserWhereUniqueInput!, create: PunbbUserCreateInput!, update: PunbbUserUpdateInput!): PunbbUser!
  deletePunbbUser(where: PunbbUserWhereUniqueInput!): PunbbUser
  deleteManyPunbbUsers(where: PunbbUserWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type PunbbBan {
  id: Int!
  email: String
  expire: Int
  ip: String
  message: String
  username: String
}

type PunbbBanConnection {
  pageInfo: PageInfo!
  edges: [PunbbBanEdge]!
  aggregate: AggregatePunbbBan!
}

input PunbbBanCreateInput {
  id: Int
  email: String
  expire: Int
  ip: String
  message: String
  username: String
}

type PunbbBanEdge {
  node: PunbbBan!
  cursor: String!
}

enum PunbbBanOrderByInput {
  id_ASC
  id_DESC
  email_ASC
  email_DESC
  expire_ASC
  expire_DESC
  ip_ASC
  ip_DESC
  message_ASC
  message_DESC
  username_ASC
  username_DESC
}

type PunbbBanPreviousValues {
  id: Int!
  email: String
  expire: Int
  ip: String
  message: String
  username: String
}

type PunbbBanSubscriptionPayload {
  mutation: MutationType!
  node: PunbbBan
  updatedFields: [String!]
  previousValues: PunbbBanPreviousValues
}

input PunbbBanSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbBanWhereInput
  AND: [PunbbBanSubscriptionWhereInput!]
  OR: [PunbbBanSubscriptionWhereInput!]
  NOT: [PunbbBanSubscriptionWhereInput!]
}

input PunbbBanUpdateInput {
  email: String
  expire: Int
  ip: String
  message: String
  username: String
}

input PunbbBanUpdateManyMutationInput {
  email: String
  expire: Int
  ip: String
  message: String
  username: String
}

input PunbbBanWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  email: String
  email_not: String
  email_in: [String!]
  email_not_in: [String!]
  email_lt: String
  email_lte: String
  email_gt: String
  email_gte: String
  email_contains: String
  email_not_contains: String
  email_starts_with: String
  email_not_starts_with: String
  email_ends_with: String
  email_not_ends_with: String
  expire: Int
  expire_not: Int
  expire_in: [Int!]
  expire_not_in: [Int!]
  expire_lt: Int
  expire_lte: Int
  expire_gt: Int
  expire_gte: Int
  ip: String
  ip_not: String
  ip_in: [String!]
  ip_not_in: [String!]
  ip_lt: String
  ip_lte: String
  ip_gt: String
  ip_gte: String
  ip_contains: String
  ip_not_contains: String
  ip_starts_with: String
  ip_not_starts_with: String
  ip_ends_with: String
  ip_not_ends_with: String
  message: String
  message_not: String
  message_in: [String!]
  message_not_in: [String!]
  message_lt: String
  message_lte: String
  message_gt: String
  message_gte: String
  message_contains: String
  message_not_contains: String
  message_starts_with: String
  message_not_starts_with: String
  message_ends_with: String
  message_not_ends_with: String
  username: String
  username_not: String
  username_in: [String!]
  username_not_in: [String!]
  username_lt: String
  username_lte: String
  username_gt: String
  username_gte: String
  username_contains: String
  username_not_contains: String
  username_starts_with: String
  username_not_starts_with: String
  username_ends_with: String
  username_not_ends_with: String
  AND: [PunbbBanWhereInput!]
  OR: [PunbbBanWhereInput!]
  NOT: [PunbbBanWhereInput!]
}

input PunbbBanWhereUniqueInput {
  id: Int
}

type PunbbCategory {
  id: Int!
  catName: String!
  dispPosition: Int!
}

type PunbbCategoryConnection {
  pageInfo: PageInfo!
  edges: [PunbbCategoryEdge]!
  aggregate: AggregatePunbbCategory!
}

input PunbbCategoryCreateInput {
  id: Int
  catName: String
  dispPosition: Int
}

type PunbbCategoryEdge {
  node: PunbbCategory!
  cursor: String!
}

enum PunbbCategoryOrderByInput {
  id_ASC
  id_DESC
  catName_ASC
  catName_DESC
  dispPosition_ASC
  dispPosition_DESC
}

type PunbbCategoryPreviousValues {
  id: Int!
  catName: String!
  dispPosition: Int!
}

type PunbbCategorySubscriptionPayload {
  mutation: MutationType!
  node: PunbbCategory
  updatedFields: [String!]
  previousValues: PunbbCategoryPreviousValues
}

input PunbbCategorySubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbCategoryWhereInput
  AND: [PunbbCategorySubscriptionWhereInput!]
  OR: [PunbbCategorySubscriptionWhereInput!]
  NOT: [PunbbCategorySubscriptionWhereInput!]
}

input PunbbCategoryUpdateInput {
  catName: String
  dispPosition: Int
}

input PunbbCategoryUpdateManyMutationInput {
  catName: String
  dispPosition: Int
}

input PunbbCategoryWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  catName: String
  catName_not: String
  catName_in: [String!]
  catName_not_in: [String!]
  catName_lt: String
  catName_lte: String
  catName_gt: String
  catName_gte: String
  catName_contains: String
  catName_not_contains: String
  catName_starts_with: String
  catName_not_starts_with: String
  catName_ends_with: String
  catName_not_ends_with: String
  dispPosition: Int
  dispPosition_not: Int
  dispPosition_in: [Int!]
  dispPosition_not_in: [Int!]
  dispPosition_lt: Int
  dispPosition_lte: Int
  dispPosition_gt: Int
  dispPosition_gte: Int
  AND: [PunbbCategoryWhereInput!]
  OR: [PunbbCategoryWhereInput!]
  NOT: [PunbbCategoryWhereInput!]
}

input PunbbCategoryWhereUniqueInput {
  id: Int
}

type PunbbForum {
  id: Int!
  catId: Int!
  dispPosition: Int!
  forumDesc: String
  forumName: String!
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  moderators: String
  redirectUrl: String
  sortBy: Boolean!
}

type PunbbForumConnection {
  pageInfo: PageInfo!
  edges: [PunbbForumEdge]!
  aggregate: AggregatePunbbForum!
}

input PunbbForumCreateInput {
  id: Int
  catId: Int
  dispPosition: Int
  forumDesc: String
  forumName: String
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  moderators: String
  redirectUrl: String
  sortBy: Boolean
}

type PunbbForumEdge {
  node: PunbbForum!
  cursor: String!
}

enum PunbbForumOrderByInput {
  id_ASC
  id_DESC
  catId_ASC
  catId_DESC
  dispPosition_ASC
  dispPosition_DESC
  forumDesc_ASC
  forumDesc_DESC
  forumName_ASC
  forumName_DESC
  lastPost_ASC
  lastPost_DESC
  lastPoster_ASC
  lastPoster_DESC
  lastPostId_ASC
  lastPostId_DESC
  moderators_ASC
  moderators_DESC
  redirectUrl_ASC
  redirectUrl_DESC
  sortBy_ASC
  sortBy_DESC
}

type PunbbForumPreviousValues {
  id: Int!
  catId: Int!
  dispPosition: Int!
  forumDesc: String
  forumName: String!
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  moderators: String
  redirectUrl: String
  sortBy: Boolean!
}

type PunbbForumSubscriptionPayload {
  mutation: MutationType!
  node: PunbbForum
  updatedFields: [String!]
  previousValues: PunbbForumPreviousValues
}

input PunbbForumSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbForumWhereInput
  AND: [PunbbForumSubscriptionWhereInput!]
  OR: [PunbbForumSubscriptionWhereInput!]
  NOT: [PunbbForumSubscriptionWhereInput!]
}

input PunbbForumUpdateInput {
  catId: Int
  dispPosition: Int
  forumDesc: String
  forumName: String
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  moderators: String
  redirectUrl: String
  sortBy: Boolean
}

input PunbbForumUpdateManyMutationInput {
  catId: Int
  dispPosition: Int
  forumDesc: String
  forumName: String
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  moderators: String
  redirectUrl: String
  sortBy: Boolean
}

input PunbbForumWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  catId: Int
  catId_not: Int
  catId_in: [Int!]
  catId_not_in: [Int!]
  catId_lt: Int
  catId_lte: Int
  catId_gt: Int
  catId_gte: Int
  dispPosition: Int
  dispPosition_not: Int
  dispPosition_in: [Int!]
  dispPosition_not_in: [Int!]
  dispPosition_lt: Int
  dispPosition_lte: Int
  dispPosition_gt: Int
  dispPosition_gte: Int
  forumDesc: String
  forumDesc_not: String
  forumDesc_in: [String!]
  forumDesc_not_in: [String!]
  forumDesc_lt: String
  forumDesc_lte: String
  forumDesc_gt: String
  forumDesc_gte: String
  forumDesc_contains: String
  forumDesc_not_contains: String
  forumDesc_starts_with: String
  forumDesc_not_starts_with: String
  forumDesc_ends_with: String
  forumDesc_not_ends_with: String
  forumName: String
  forumName_not: String
  forumName_in: [String!]
  forumName_not_in: [String!]
  forumName_lt: String
  forumName_lte: String
  forumName_gt: String
  forumName_gte: String
  forumName_contains: String
  forumName_not_contains: String
  forumName_starts_with: String
  forumName_not_starts_with: String
  forumName_ends_with: String
  forumName_not_ends_with: String
  lastPost: Int
  lastPost_not: Int
  lastPost_in: [Int!]
  lastPost_not_in: [Int!]
  lastPost_lt: Int
  lastPost_lte: Int
  lastPost_gt: Int
  lastPost_gte: Int
  lastPoster: String
  lastPoster_not: String
  lastPoster_in: [String!]
  lastPoster_not_in: [String!]
  lastPoster_lt: String
  lastPoster_lte: String
  lastPoster_gt: String
  lastPoster_gte: String
  lastPoster_contains: String
  lastPoster_not_contains: String
  lastPoster_starts_with: String
  lastPoster_not_starts_with: String
  lastPoster_ends_with: String
  lastPoster_not_ends_with: String
  lastPostId: Int
  lastPostId_not: Int
  lastPostId_in: [Int!]
  lastPostId_not_in: [Int!]
  lastPostId_lt: Int
  lastPostId_lte: Int
  lastPostId_gt: Int
  lastPostId_gte: Int
  moderators: String
  moderators_not: String
  moderators_in: [String!]
  moderators_not_in: [String!]
  moderators_lt: String
  moderators_lte: String
  moderators_gt: String
  moderators_gte: String
  moderators_contains: String
  moderators_not_contains: String
  moderators_starts_with: String
  moderators_not_starts_with: String
  moderators_ends_with: String
  moderators_not_ends_with: String
  redirectUrl: String
  redirectUrl_not: String
  redirectUrl_in: [String!]
  redirectUrl_not_in: [String!]
  redirectUrl_lt: String
  redirectUrl_lte: String
  redirectUrl_gt: String
  redirectUrl_gte: String
  redirectUrl_contains: String
  redirectUrl_not_contains: String
  redirectUrl_starts_with: String
  redirectUrl_not_starts_with: String
  redirectUrl_ends_with: String
  redirectUrl_not_ends_with: String
  sortBy: Boolean
  sortBy_not: Boolean
  AND: [PunbbForumWhereInput!]
  OR: [PunbbForumWhereInput!]
  NOT: [PunbbForumWhereInput!]
}

input PunbbForumWhereUniqueInput {
  id: Int
}

type PunbbOnline {
  ident: String!
  idle: Boolean!
  logged: Int!
  userId: Int!
}

type PunbbOnlineConnection {
  pageInfo: PageInfo!
  edges: [PunbbOnlineEdge]!
  aggregate: AggregatePunbbOnline!
}

input PunbbOnlineCreateInput {
  ident: String
  idle: Boolean
  logged: Int
  userId: Int
}

type PunbbOnlineEdge {
  node: PunbbOnline!
  cursor: String!
}

enum PunbbOnlineOrderByInput {
  ident_ASC
  ident_DESC
  idle_ASC
  idle_DESC
  logged_ASC
  logged_DESC
  userId_ASC
  userId_DESC
}

type PunbbOnlinePreviousValues {
  ident: String!
  idle: Boolean!
  logged: Int!
  userId: Int!
}

type PunbbOnlineSubscriptionPayload {
  mutation: MutationType!
  node: PunbbOnline
  updatedFields: [String!]
  previousValues: PunbbOnlinePreviousValues
}

input PunbbOnlineSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbOnlineWhereInput
  AND: [PunbbOnlineSubscriptionWhereInput!]
  OR: [PunbbOnlineSubscriptionWhereInput!]
  NOT: [PunbbOnlineSubscriptionWhereInput!]
}

input PunbbOnlineUpdateInput {
  ident: String
  idle: Boolean
  logged: Int
}

input PunbbOnlineUpdateManyMutationInput {
  ident: String
  idle: Boolean
  logged: Int
}

input PunbbOnlineWhereInput {
  ident: String
  ident_not: String
  ident_in: [String!]
  ident_not_in: [String!]
  ident_lt: String
  ident_lte: String
  ident_gt: String
  ident_gte: String
  ident_contains: String
  ident_not_contains: String
  ident_starts_with: String
  ident_not_starts_with: String
  ident_ends_with: String
  ident_not_ends_with: String
  idle: Boolean
  idle_not: Boolean
  logged: Int
  logged_not: Int
  logged_in: [Int!]
  logged_not_in: [Int!]
  logged_lt: Int
  logged_lte: Int
  logged_gt: Int
  logged_gte: Int
  userId: Int
  userId_not: Int
  userId_in: [Int!]
  userId_not_in: [Int!]
  userId_lt: Int
  userId_lte: Int
  userId_gt: Int
  userId_gte: Int
  AND: [PunbbOnlineWhereInput!]
  OR: [PunbbOnlineWhereInput!]
  NOT: [PunbbOnlineWhereInput!]
}

input PunbbOnlineWhereUniqueInput {
  userId: Int
}

type PunbbPost {
  id: Int!
  edited: Int
  editedBy: String
  hideSmilies: Boolean!
  message: String!
  posted: Int!
  poster: String!
  posterEmail: String
  posterId: Int!
  posterIp: String
  topicId: Int!
}

type PunbbPostConnection {
  pageInfo: PageInfo!
  edges: [PunbbPostEdge]!
  aggregate: AggregatePunbbPost!
}

input PunbbPostCreateInput {
  id: Int
  edited: Int
  editedBy: String
  hideSmilies: Boolean
  message: String!
  posted: Int
  poster: String
  posterEmail: String
  posterId: Int
  posterIp: String
  topicId: Int
}

type PunbbPostEdge {
  node: PunbbPost!
  cursor: String!
}

enum PunbbPostOrderByInput {
  id_ASC
  id_DESC
  edited_ASC
  edited_DESC
  editedBy_ASC
  editedBy_DESC
  hideSmilies_ASC
  hideSmilies_DESC
  message_ASC
  message_DESC
  posted_ASC
  posted_DESC
  poster_ASC
  poster_DESC
  posterEmail_ASC
  posterEmail_DESC
  posterId_ASC
  posterId_DESC
  posterIp_ASC
  posterIp_DESC
  topicId_ASC
  topicId_DESC
}

type PunbbPostPreviousValues {
  id: Int!
  edited: Int
  editedBy: String
  hideSmilies: Boolean!
  message: String!
  posted: Int!
  poster: String!
  posterEmail: String
  posterId: Int!
  posterIp: String
  topicId: Int!
}

type PunbbPostSubscriptionPayload {
  mutation: MutationType!
  node: PunbbPost
  updatedFields: [String!]
  previousValues: PunbbPostPreviousValues
}

input PunbbPostSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbPostWhereInput
  AND: [PunbbPostSubscriptionWhereInput!]
  OR: [PunbbPostSubscriptionWhereInput!]
  NOT: [PunbbPostSubscriptionWhereInput!]
}

input PunbbPostUpdateInput {
  edited: Int
  editedBy: String
  hideSmilies: Boolean
  message: String
  posted: Int
  poster: String
  posterEmail: String
  posterId: Int
  posterIp: String
  topicId: Int
}

input PunbbPostUpdateManyMutationInput {
  edited: Int
  editedBy: String
  hideSmilies: Boolean
  message: String
  posted: Int
  poster: String
  posterEmail: String
  posterId: Int
  posterIp: String
  topicId: Int
}

input PunbbPostWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  edited: Int
  edited_not: Int
  edited_in: [Int!]
  edited_not_in: [Int!]
  edited_lt: Int
  edited_lte: Int
  edited_gt: Int
  edited_gte: Int
  editedBy: String
  editedBy_not: String
  editedBy_in: [String!]
  editedBy_not_in: [String!]
  editedBy_lt: String
  editedBy_lte: String
  editedBy_gt: String
  editedBy_gte: String
  editedBy_contains: String
  editedBy_not_contains: String
  editedBy_starts_with: String
  editedBy_not_starts_with: String
  editedBy_ends_with: String
  editedBy_not_ends_with: String
  hideSmilies: Boolean
  hideSmilies_not: Boolean
  message: String
  message_not: String
  message_in: [String!]
  message_not_in: [String!]
  message_lt: String
  message_lte: String
  message_gt: String
  message_gte: String
  message_contains: String
  message_not_contains: String
  message_starts_with: String
  message_not_starts_with: String
  message_ends_with: String
  message_not_ends_with: String
  posted: Int
  posted_not: Int
  posted_in: [Int!]
  posted_not_in: [Int!]
  posted_lt: Int
  posted_lte: Int
  posted_gt: Int
  posted_gte: Int
  poster: String
  poster_not: String
  poster_in: [String!]
  poster_not_in: [String!]
  poster_lt: String
  poster_lte: String
  poster_gt: String
  poster_gte: String
  poster_contains: String
  poster_not_contains: String
  poster_starts_with: String
  poster_not_starts_with: String
  poster_ends_with: String
  poster_not_ends_with: String
  posterEmail: String
  posterEmail_not: String
  posterEmail_in: [String!]
  posterEmail_not_in: [String!]
  posterEmail_lt: String
  posterEmail_lte: String
  posterEmail_gt: String
  posterEmail_gte: String
  posterEmail_contains: String
  posterEmail_not_contains: String
  posterEmail_starts_with: String
  posterEmail_not_starts_with: String
  posterEmail_ends_with: String
  posterEmail_not_ends_with: String
  posterId: Int
  posterId_not: Int
  posterId_in: [Int!]
  posterId_not_in: [Int!]
  posterId_lt: Int
  posterId_lte: Int
  posterId_gt: Int
  posterId_gte: Int
  posterIp: String
  posterIp_not: String
  posterIp_in: [String!]
  posterIp_not_in: [String!]
  posterIp_lt: String
  posterIp_lte: String
  posterIp_gt: String
  posterIp_gte: String
  posterIp_contains: String
  posterIp_not_contains: String
  posterIp_starts_with: String
  posterIp_not_starts_with: String
  posterIp_ends_with: String
  posterIp_not_ends_with: String
  topicId: Int
  topicId_not: Int
  topicId_in: [Int!]
  topicId_not_in: [Int!]
  topicId_lt: Int
  topicId_lte: Int
  topicId_gt: Int
  topicId_gte: Int
  AND: [PunbbPostWhereInput!]
  OR: [PunbbPostWhereInput!]
  NOT: [PunbbPostWhereInput!]
}

input PunbbPostWhereUniqueInput {
  id: Int
}

type PunbbTopic {
  id: Int!
  closed: Boolean!
  forumId: Int!
  lastPost: Int!
  lastPoster: String
  lastPostId: Int!
  movedTo: Int
  no: String!
  posted: Int!
  poster: String!
  question: String!
  sticky: Boolean!
  subject: String!
  yes: String!
}

type PunbbTopicConnection {
  pageInfo: PageInfo!
  edges: [PunbbTopicEdge]!
  aggregate: AggregatePunbbTopic!
}

input PunbbTopicCreateInput {
  id: Int
  closed: Boolean
  forumId: Int
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  movedTo: Int
  no: String!
  posted: Int
  poster: String
  question: String!
  sticky: Boolean
  subject: String
  yes: String!
}

type PunbbTopicEdge {
  node: PunbbTopic!
  cursor: String!
}

enum PunbbTopicOrderByInput {
  id_ASC
  id_DESC
  closed_ASC
  closed_DESC
  forumId_ASC
  forumId_DESC
  lastPost_ASC
  lastPost_DESC
  lastPoster_ASC
  lastPoster_DESC
  lastPostId_ASC
  lastPostId_DESC
  movedTo_ASC
  movedTo_DESC
  no_ASC
  no_DESC
  posted_ASC
  posted_DESC
  poster_ASC
  poster_DESC
  question_ASC
  question_DESC
  sticky_ASC
  sticky_DESC
  subject_ASC
  subject_DESC
  yes_ASC
  yes_DESC
}

type PunbbTopicPreviousValues {
  id: Int!
  closed: Boolean!
  forumId: Int!
  lastPost: Int!
  lastPoster: String
  lastPostId: Int!
  movedTo: Int
  no: String!
  posted: Int!
  poster: String!
  question: String!
  sticky: Boolean!
  subject: String!
  yes: String!
}

type PunbbTopicSubscriptionPayload {
  mutation: MutationType!
  node: PunbbTopic
  updatedFields: [String!]
  previousValues: PunbbTopicPreviousValues
}

input PunbbTopicSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbTopicWhereInput
  AND: [PunbbTopicSubscriptionWhereInput!]
  OR: [PunbbTopicSubscriptionWhereInput!]
  NOT: [PunbbTopicSubscriptionWhereInput!]
}

input PunbbTopicUpdateInput {
  closed: Boolean
  forumId: Int
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  movedTo: Int
  no: String
  posted: Int
  poster: String
  question: String
  sticky: Boolean
  subject: String
  yes: String
}

input PunbbTopicUpdateManyMutationInput {
  closed: Boolean
  forumId: Int
  lastPost: Int
  lastPoster: String
  lastPostId: Int
  movedTo: Int
  no: String
  posted: Int
  poster: String
  question: String
  sticky: Boolean
  subject: String
  yes: String
}

input PunbbTopicWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  closed: Boolean
  closed_not: Boolean
  forumId: Int
  forumId_not: Int
  forumId_in: [Int!]
  forumId_not_in: [Int!]
  forumId_lt: Int
  forumId_lte: Int
  forumId_gt: Int
  forumId_gte: Int
  lastPost: Int
  lastPost_not: Int
  lastPost_in: [Int!]
  lastPost_not_in: [Int!]
  lastPost_lt: Int
  lastPost_lte: Int
  lastPost_gt: Int
  lastPost_gte: Int
  lastPoster: String
  lastPoster_not: String
  lastPoster_in: [String!]
  lastPoster_not_in: [String!]
  lastPoster_lt: String
  lastPoster_lte: String
  lastPoster_gt: String
  lastPoster_gte: String
  lastPoster_contains: String
  lastPoster_not_contains: String
  lastPoster_starts_with: String
  lastPoster_not_starts_with: String
  lastPoster_ends_with: String
  lastPoster_not_ends_with: String
  lastPostId: Int
  lastPostId_not: Int
  lastPostId_in: [Int!]
  lastPostId_not_in: [Int!]
  lastPostId_lt: Int
  lastPostId_lte: Int
  lastPostId_gt: Int
  lastPostId_gte: Int
  movedTo: Int
  movedTo_not: Int
  movedTo_in: [Int!]
  movedTo_not_in: [Int!]
  movedTo_lt: Int
  movedTo_lte: Int
  movedTo_gt: Int
  movedTo_gte: Int
  no: String
  no_not: String
  no_in: [String!]
  no_not_in: [String!]
  no_lt: String
  no_lte: String
  no_gt: String
  no_gte: String
  no_contains: String
  no_not_contains: String
  no_starts_with: String
  no_not_starts_with: String
  no_ends_with: String
  no_not_ends_with: String
  posted: Int
  posted_not: Int
  posted_in: [Int!]
  posted_not_in: [Int!]
  posted_lt: Int
  posted_lte: Int
  posted_gt: Int
  posted_gte: Int
  poster: String
  poster_not: String
  poster_in: [String!]
  poster_not_in: [String!]
  poster_lt: String
  poster_lte: String
  poster_gt: String
  poster_gte: String
  poster_contains: String
  poster_not_contains: String
  poster_starts_with: String
  poster_not_starts_with: String
  poster_ends_with: String
  poster_not_ends_with: String
  question: String
  question_not: String
  question_in: [String!]
  question_not_in: [String!]
  question_lt: String
  question_lte: String
  question_gt: String
  question_gte: String
  question_contains: String
  question_not_contains: String
  question_starts_with: String
  question_not_starts_with: String
  question_ends_with: String
  question_not_ends_with: String
  sticky: Boolean
  sticky_not: Boolean
  subject: String
  subject_not: String
  subject_in: [String!]
  subject_not_in: [String!]
  subject_lt: String
  subject_lte: String
  subject_gt: String
  subject_gte: String
  subject_contains: String
  subject_not_contains: String
  subject_starts_with: String
  subject_not_starts_with: String
  subject_ends_with: String
  subject_not_ends_with: String
  yes: String
  yes_not: String
  yes_in: [String!]
  yes_not_in: [String!]
  yes_lt: String
  yes_lte: String
  yes_gt: String
  yes_gte: String
  yes_contains: String
  yes_not_contains: String
  yes_starts_with: String
  yes_not_starts_with: String
  yes_ends_with: String
  yes_not_ends_with: String
  AND: [PunbbTopicWhereInput!]
  OR: [PunbbTopicWhereInput!]
  NOT: [PunbbTopicWhereInput!]
}

input PunbbTopicWhereUniqueInput {
  id: Int
}

type PunbbUploaded {
  id: Int!
  data: Int!
  descr: String!
  downs: Int!
  file: String!
  size: Int!
  uid: Int!
  user: String!
  userStat: String!
}

type PunbbUploadedConnection {
  pageInfo: PageInfo!
  edges: [PunbbUploadedEdge]!
  aggregate: AggregatePunbbUploaded!
}

input PunbbUploadedCreateInput {
  id: Int
  data: Int!
  descr: String!
  downs: Int!
  file: String!
  size: Int!
  uid: Int!
  user: String!
  userStat: String!
}

type PunbbUploadedEdge {
  node: PunbbUploaded!
  cursor: String!
}

enum PunbbUploadedOrderByInput {
  id_ASC
  id_DESC
  data_ASC
  data_DESC
  descr_ASC
  descr_DESC
  downs_ASC
  downs_DESC
  file_ASC
  file_DESC
  size_ASC
  size_DESC
  uid_ASC
  uid_DESC
  user_ASC
  user_DESC
  userStat_ASC
  userStat_DESC
}

type PunbbUploadedPreviousValues {
  id: Int!
  data: Int!
  descr: String!
  downs: Int!
  file: String!
  size: Int!
  uid: Int!
  user: String!
  userStat: String!
}

type PunbbUploadedSubscriptionPayload {
  mutation: MutationType!
  node: PunbbUploaded
  updatedFields: [String!]
  previousValues: PunbbUploadedPreviousValues
}

input PunbbUploadedSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbUploadedWhereInput
  AND: [PunbbUploadedSubscriptionWhereInput!]
  OR: [PunbbUploadedSubscriptionWhereInput!]
  NOT: [PunbbUploadedSubscriptionWhereInput!]
}

input PunbbUploadedUpdateInput {
  data: Int
  descr: String
  downs: Int
  file: String
  size: Int
  uid: Int
  user: String
  userStat: String
}

input PunbbUploadedUpdateManyMutationInput {
  data: Int
  descr: String
  downs: Int
  file: String
  size: Int
  uid: Int
  user: String
  userStat: String
}

input PunbbUploadedWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  data: Int
  data_not: Int
  data_in: [Int!]
  data_not_in: [Int!]
  data_lt: Int
  data_lte: Int
  data_gt: Int
  data_gte: Int
  descr: String
  descr_not: String
  descr_in: [String!]
  descr_not_in: [String!]
  descr_lt: String
  descr_lte: String
  descr_gt: String
  descr_gte: String
  descr_contains: String
  descr_not_contains: String
  descr_starts_with: String
  descr_not_starts_with: String
  descr_ends_with: String
  descr_not_ends_with: String
  downs: Int
  downs_not: Int
  downs_in: [Int!]
  downs_not_in: [Int!]
  downs_lt: Int
  downs_lte: Int
  downs_gt: Int
  downs_gte: Int
  file: String
  file_not: String
  file_in: [String!]
  file_not_in: [String!]
  file_lt: String
  file_lte: String
  file_gt: String
  file_gte: String
  file_contains: String
  file_not_contains: String
  file_starts_with: String
  file_not_starts_with: String
  file_ends_with: String
  file_not_ends_with: String
  size: Int
  size_not: Int
  size_in: [Int!]
  size_not_in: [Int!]
  size_lt: Int
  size_lte: Int
  size_gt: Int
  size_gte: Int
  uid: Int
  uid_not: Int
  uid_in: [Int!]
  uid_not_in: [Int!]
  uid_lt: Int
  uid_lte: Int
  uid_gt: Int
  uid_gte: Int
  user: String
  user_not: String
  user_in: [String!]
  user_not_in: [String!]
  user_lt: String
  user_lte: String
  user_gt: String
  user_gte: String
  user_contains: String
  user_not_contains: String
  user_starts_with: String
  user_not_starts_with: String
  user_ends_with: String
  user_not_ends_with: String
  userStat: String
  userStat_not: String
  userStat_in: [String!]
  userStat_not_in: [String!]
  userStat_lt: String
  userStat_lte: String
  userStat_gt: String
  userStat_gte: String
  userStat_contains: String
  userStat_not_contains: String
  userStat_starts_with: String
  userStat_not_starts_with: String
  userStat_ends_with: String
  userStat_not_ends_with: String
  AND: [PunbbUploadedWhereInput!]
  OR: [PunbbUploadedWhereInput!]
  NOT: [PunbbUploadedWhereInput!]
}

input PunbbUploadedWhereUniqueInput {
  id: Int
}

type PunbbUser {
  id: Int!
  activateKey: String
  activateString: String
  adminNote: String
  aim: String
  dispPosts: Boolean
  dispTopics: Boolean
  email: String!
  emailSetting: Boolean!
  groupId: Int!
  icq: String
  jabber: String
  language: String!
  lastPost: Int
  lastVisit: Int!
  location: String
  msn: String
  notifyWithPost: Boolean!
  numPosts: Int!
  password: String!
  readTopics: String
  realname: String
  registered: Int!
  registrationIp: String!
  savePass: Boolean!
  showAvatars: Boolean!
  showImg: Boolean!
  showImgSig: Boolean!
  showSig: Boolean!
  showSmilies: Boolean!
  signature: String
  style: String!
  timezone: Float!
  title: String
  url: String
  useAvatar: Boolean!
  username: String!
  yahoo: String
}

type PunbbUserConnection {
  pageInfo: PageInfo!
  edges: [PunbbUserEdge]!
  aggregate: AggregatePunbbUser!
}

input PunbbUserCreateInput {
  id: Int
  activateKey: String
  activateString: String
  adminNote: String
  aim: String
  dispPosts: Boolean
  dispTopics: Boolean
  email: String
  emailSetting: Boolean
  groupId: Int
  icq: String
  jabber: String
  language: String
  lastPost: Int
  lastVisit: Int
  location: String
  msn: String
  notifyWithPost: Boolean
  numPosts: Int
  password: String
  readTopics: String
  realname: String
  registered: Int
  registrationIp: String
  savePass: Boolean
  showAvatars: Boolean
  showImg: Boolean
  showImgSig: Boolean
  showSig: Boolean
  showSmilies: Boolean
  signature: String
  style: String
  timezone: Float
  title: String
  url: String
  useAvatar: Boolean
  username: String
  yahoo: String
}

type PunbbUserEdge {
  node: PunbbUser!
  cursor: String!
}

enum PunbbUserOrderByInput {
  id_ASC
  id_DESC
  activateKey_ASC
  activateKey_DESC
  activateString_ASC
  activateString_DESC
  adminNote_ASC
  adminNote_DESC
  aim_ASC
  aim_DESC
  dispPosts_ASC
  dispPosts_DESC
  dispTopics_ASC
  dispTopics_DESC
  email_ASC
  email_DESC
  emailSetting_ASC
  emailSetting_DESC
  groupId_ASC
  groupId_DESC
  icq_ASC
  icq_DESC
  jabber_ASC
  jabber_DESC
  language_ASC
  language_DESC
  lastPost_ASC
  lastPost_DESC
  lastVisit_ASC
  lastVisit_DESC
  location_ASC
  location_DESC
  msn_ASC
  msn_DESC
  notifyWithPost_ASC
  notifyWithPost_DESC
  numPosts_ASC
  numPosts_DESC
  password_ASC
  password_DESC
  readTopics_ASC
  readTopics_DESC
  realname_ASC
  realname_DESC
  registered_ASC
  registered_DESC
  registrationIp_ASC
  registrationIp_DESC
  savePass_ASC
  savePass_DESC
  showAvatars_ASC
  showAvatars_DESC
  showImg_ASC
  showImg_DESC
  showImgSig_ASC
  showImgSig_DESC
  showSig_ASC
  showSig_DESC
  showSmilies_ASC
  showSmilies_DESC
  signature_ASC
  signature_DESC
  style_ASC
  style_DESC
  timezone_ASC
  timezone_DESC
  title_ASC
  title_DESC
  url_ASC
  url_DESC
  useAvatar_ASC
  useAvatar_DESC
  username_ASC
  username_DESC
  yahoo_ASC
  yahoo_DESC
}

type PunbbUserPreviousValues {
  id: Int!
  activateKey: String
  activateString: String
  adminNote: String
  aim: String
  dispPosts: Boolean
  dispTopics: Boolean
  email: String!
  emailSetting: Boolean!
  groupId: Int!
  icq: String
  jabber: String
  language: String!
  lastPost: Int
  lastVisit: Int!
  location: String
  msn: String
  notifyWithPost: Boolean!
  numPosts: Int!
  password: String!
  readTopics: String
  realname: String
  registered: Int!
  registrationIp: String!
  savePass: Boolean!
  showAvatars: Boolean!
  showImg: Boolean!
  showImgSig: Boolean!
  showSig: Boolean!
  showSmilies: Boolean!
  signature: String
  style: String!
  timezone: Float!
  title: String
  url: String
  useAvatar: Boolean!
  username: String!
  yahoo: String
}

type PunbbUserSubscriptionPayload {
  mutation: MutationType!
  node: PunbbUser
  updatedFields: [String!]
  previousValues: PunbbUserPreviousValues
}

input PunbbUserSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: PunbbUserWhereInput
  AND: [PunbbUserSubscriptionWhereInput!]
  OR: [PunbbUserSubscriptionWhereInput!]
  NOT: [PunbbUserSubscriptionWhereInput!]
}

input PunbbUserUpdateInput {
  activateKey: String
  activateString: String
  adminNote: String
  aim: String
  dispPosts: Boolean
  dispTopics: Boolean
  email: String
  emailSetting: Boolean
  groupId: Int
  icq: String
  jabber: String
  language: String
  lastPost: Int
  lastVisit: Int
  location: String
  msn: String
  notifyWithPost: Boolean
  numPosts: Int
  password: String
  readTopics: String
  realname: String
  registered: Int
  registrationIp: String
  savePass: Boolean
  showAvatars: Boolean
  showImg: Boolean
  showImgSig: Boolean
  showSig: Boolean
  showSmilies: Boolean
  signature: String
  style: String
  timezone: Float
  title: String
  url: String
  useAvatar: Boolean
  username: String
  yahoo: String
}

input PunbbUserUpdateManyMutationInput {
  activateKey: String
  activateString: String
  adminNote: String
  aim: String
  dispPosts: Boolean
  dispTopics: Boolean
  email: String
  emailSetting: Boolean
  groupId: Int
  icq: String
  jabber: String
  language: String
  lastPost: Int
  lastVisit: Int
  location: String
  msn: String
  notifyWithPost: Boolean
  numPosts: Int
  password: String
  readTopics: String
  realname: String
  registered: Int
  registrationIp: String
  savePass: Boolean
  showAvatars: Boolean
  showImg: Boolean
  showImgSig: Boolean
  showSig: Boolean
  showSmilies: Boolean
  signature: String
  style: String
  timezone: Float
  title: String
  url: String
  useAvatar: Boolean
  username: String
  yahoo: String
}

input PunbbUserWhereInput {
  id: Int
  id_not: Int
  id_in: [Int!]
  id_not_in: [Int!]
  id_lt: Int
  id_lte: Int
  id_gt: Int
  id_gte: Int
  activateKey: String
  activateKey_not: String
  activateKey_in: [String!]
  activateKey_not_in: [String!]
  activateKey_lt: String
  activateKey_lte: String
  activateKey_gt: String
  activateKey_gte: String
  activateKey_contains: String
  activateKey_not_contains: String
  activateKey_starts_with: String
  activateKey_not_starts_with: String
  activateKey_ends_with: String
  activateKey_not_ends_with: String
  activateString: String
  activateString_not: String
  activateString_in: [String!]
  activateString_not_in: [String!]
  activateString_lt: String
  activateString_lte: String
  activateString_gt: String
  activateString_gte: String
  activateString_contains: String
  activateString_not_contains: String
  activateString_starts_with: String
  activateString_not_starts_with: String
  activateString_ends_with: String
  activateString_not_ends_with: String
  adminNote: String
  adminNote_not: String
  adminNote_in: [String!]
  adminNote_not_in: [String!]
  adminNote_lt: String
  adminNote_lte: String
  adminNote_gt: String
  adminNote_gte: String
  adminNote_contains: String
  adminNote_not_contains: String
  adminNote_starts_with: String
  adminNote_not_starts_with: String
  adminNote_ends_with: String
  adminNote_not_ends_with: String
  aim: String
  aim_not: String
  aim_in: [String!]
  aim_not_in: [String!]
  aim_lt: String
  aim_lte: String
  aim_gt: String
  aim_gte: String
  aim_contains: String
  aim_not_contains: String
  aim_starts_with: String
  aim_not_starts_with: String
  aim_ends_with: String
  aim_not_ends_with: String
  dispPosts: Boolean
  dispPosts_not: Boolean
  dispTopics: Boolean
  dispTopics_not: Boolean
  email: String
  email_not: String
  email_in: [String!]
  email_not_in: [String!]
  email_lt: String
  email_lte: String
  email_gt: String
  email_gte: String
  email_contains: String
  email_not_contains: String
  email_starts_with: String
  email_not_starts_with: String
  email_ends_with: String
  email_not_ends_with: String
  emailSetting: Boolean
  emailSetting_not: Boolean
  groupId: Int
  groupId_not: Int
  groupId_in: [Int!]
  groupId_not_in: [Int!]
  groupId_lt: Int
  groupId_lte: Int
  groupId_gt: Int
  groupId_gte: Int
  icq: String
  icq_not: String
  icq_in: [String!]
  icq_not_in: [String!]
  icq_lt: String
  icq_lte: String
  icq_gt: String
  icq_gte: String
  icq_contains: String
  icq_not_contains: String
  icq_starts_with: String
  icq_not_starts_with: String
  icq_ends_with: String
  icq_not_ends_with: String
  jabber: String
  jabber_not: String
  jabber_in: [String!]
  jabber_not_in: [String!]
  jabber_lt: String
  jabber_lte: String
  jabber_gt: String
  jabber_gte: String
  jabber_contains: String
  jabber_not_contains: String
  jabber_starts_with: String
  jabber_not_starts_with: String
  jabber_ends_with: String
  jabber_not_ends_with: String
  language: String
  language_not: String
  language_in: [String!]
  language_not_in: [String!]
  language_lt: String
  language_lte: String
  language_gt: String
  language_gte: String
  language_contains: String
  language_not_contains: String
  language_starts_with: String
  language_not_starts_with: String
  language_ends_with: String
  language_not_ends_with: String
  lastPost: Int
  lastPost_not: Int
  lastPost_in: [Int!]
  lastPost_not_in: [Int!]
  lastPost_lt: Int
  lastPost_lte: Int
  lastPost_gt: Int
  lastPost_gte: Int
  lastVisit: Int
  lastVisit_not: Int
  lastVisit_in: [Int!]
  lastVisit_not_in: [Int!]
  lastVisit_lt: Int
  lastVisit_lte: Int
  lastVisit_gt: Int
  lastVisit_gte: Int
  location: String
  location_not: String
  location_in: [String!]
  location_not_in: [String!]
  location_lt: String
  location_lte: String
  location_gt: String
  location_gte: String
  location_contains: String
  location_not_contains: String
  location_starts_with: String
  location_not_starts_with: String
  location_ends_with: String
  location_not_ends_with: String
  msn: String
  msn_not: String
  msn_in: [String!]
  msn_not_in: [String!]
  msn_lt: String
  msn_lte: String
  msn_gt: String
  msn_gte: String
  msn_contains: String
  msn_not_contains: String
  msn_starts_with: String
  msn_not_starts_with: String
  msn_ends_with: String
  msn_not_ends_with: String
  notifyWithPost: Boolean
  notifyWithPost_not: Boolean
  numPosts: Int
  numPosts_not: Int
  numPosts_in: [Int!]
  numPosts_not_in: [Int!]
  numPosts_lt: Int
  numPosts_lte: Int
  numPosts_gt: Int
  numPosts_gte: Int
  password: String
  password_not: String
  password_in: [String!]
  password_not_in: [String!]
  password_lt: String
  password_lte: String
  password_gt: String
  password_gte: String
  password_contains: String
  password_not_contains: String
  password_starts_with: String
  password_not_starts_with: String
  password_ends_with: String
  password_not_ends_with: String
  readTopics: String
  readTopics_not: String
  readTopics_in: [String!]
  readTopics_not_in: [String!]
  readTopics_lt: String
  readTopics_lte: String
  readTopics_gt: String
  readTopics_gte: String
  readTopics_contains: String
  readTopics_not_contains: String
  readTopics_starts_with: String
  readTopics_not_starts_with: String
  readTopics_ends_with: String
  readTopics_not_ends_with: String
  realname: String
  realname_not: String
  realname_in: [String!]
  realname_not_in: [String!]
  realname_lt: String
  realname_lte: String
  realname_gt: String
  realname_gte: String
  realname_contains: String
  realname_not_contains: String
  realname_starts_with: String
  realname_not_starts_with: String
  realname_ends_with: String
  realname_not_ends_with: String
  registered: Int
  registered_not: Int
  registered_in: [Int!]
  registered_not_in: [Int!]
  registered_lt: Int
  registered_lte: Int
  registered_gt: Int
  registered_gte: Int
  registrationIp: String
  registrationIp_not: String
  registrationIp_in: [String!]
  registrationIp_not_in: [String!]
  registrationIp_lt: String
  registrationIp_lte: String
  registrationIp_gt: String
  registrationIp_gte: String
  registrationIp_contains: String
  registrationIp_not_contains: String
  registrationIp_starts_with: String
  registrationIp_not_starts_with: String
  registrationIp_ends_with: String
  registrationIp_not_ends_with: String
  savePass: Boolean
  savePass_not: Boolean
  showAvatars: Boolean
  showAvatars_not: Boolean
  showImg: Boolean
  showImg_not: Boolean
  showImgSig: Boolean
  showImgSig_not: Boolean
  showSig: Boolean
  showSig_not: Boolean
  showSmilies: Boolean
  showSmilies_not: Boolean
  signature: String
  signature_not: String
  signature_in: [String!]
  signature_not_in: [String!]
  signature_lt: String
  signature_lte: String
  signature_gt: String
  signature_gte: String
  signature_contains: String
  signature_not_contains: String
  signature_starts_with: String
  signature_not_starts_with: String
  signature_ends_with: String
  signature_not_ends_with: String
  style: String
  style_not: String
  style_in: [String!]
  style_not_in: [String!]
  style_lt: String
  style_lte: String
  style_gt: String
  style_gte: String
  style_contains: String
  style_not_contains: String
  style_starts_with: String
  style_not_starts_with: String
  style_ends_with: String
  style_not_ends_with: String
  timezone: Float
  timezone_not: Float
  timezone_in: [Float!]
  timezone_not_in: [Float!]
  timezone_lt: Float
  timezone_lte: Float
  timezone_gt: Float
  timezone_gte: Float
  title: String
  title_not: String
  title_in: [String!]
  title_not_in: [String!]
  title_lt: String
  title_lte: String
  title_gt: String
  title_gte: String
  title_contains: String
  title_not_contains: String
  title_starts_with: String
  title_not_starts_with: String
  title_ends_with: String
  title_not_ends_with: String
  url: String
  url_not: String
  url_in: [String!]
  url_not_in: [String!]
  url_lt: String
  url_lte: String
  url_gt: String
  url_gte: String
  url_contains: String
  url_not_contains: String
  url_starts_with: String
  url_not_starts_with: String
  url_ends_with: String
  url_not_ends_with: String
  useAvatar: Boolean
  useAvatar_not: Boolean
  username: String
  username_not: String
  username_in: [String!]
  username_not_in: [String!]
  username_lt: String
  username_lte: String
  username_gt: String
  username_gte: String
  username_contains: String
  username_not_contains: String
  username_starts_with: String
  username_not_starts_with: String
  username_ends_with: String
  username_not_ends_with: String
  yahoo: String
  yahoo_not: String
  yahoo_in: [String!]
  yahoo_not_in: [String!]
  yahoo_lt: String
  yahoo_lte: String
  yahoo_gt: String
  yahoo_gte: String
  yahoo_contains: String
  yahoo_not_contains: String
  yahoo_starts_with: String
  yahoo_not_starts_with: String
  yahoo_ends_with: String
  yahoo_not_ends_with: String
  AND: [PunbbUserWhereInput!]
  OR: [PunbbUserWhereInput!]
  NOT: [PunbbUserWhereInput!]
}

input PunbbUserWhereUniqueInput {
  id: Int
}

type Query {
  punbbBan(where: PunbbBanWhereUniqueInput!): PunbbBan
  punbbBans(where: PunbbBanWhereInput, orderBy: PunbbBanOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbBan]!
  punbbBansConnection(where: PunbbBanWhereInput, orderBy: PunbbBanOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbBanConnection!
  punbbCategory(where: PunbbCategoryWhereUniqueInput!): PunbbCategory
  punbbCategories(where: PunbbCategoryWhereInput, orderBy: PunbbCategoryOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbCategory]!
  punbbCategoriesConnection(where: PunbbCategoryWhereInput, orderBy: PunbbCategoryOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbCategoryConnection!
  punbbForum(where: PunbbForumWhereUniqueInput!): PunbbForum
  punbbForums(where: PunbbForumWhereInput, orderBy: PunbbForumOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbForum]!
  punbbForumsConnection(where: PunbbForumWhereInput, orderBy: PunbbForumOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbForumConnection!
  punbbOnline(where: PunbbOnlineWhereUniqueInput!): PunbbOnline
  punbbOnlines(where: PunbbOnlineWhereInput, orderBy: PunbbOnlineOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbOnline]!
  punbbOnlinesConnection(where: PunbbOnlineWhereInput, orderBy: PunbbOnlineOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbOnlineConnection!
  punbbPost(where: PunbbPostWhereUniqueInput!): PunbbPost
  punbbPosts(where: PunbbPostWhereInput, orderBy: PunbbPostOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbPost]!
  punbbPostsConnection(where: PunbbPostWhereInput, orderBy: PunbbPostOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbPostConnection!
  punbbTopic(where: PunbbTopicWhereUniqueInput!): PunbbTopic
  punbbTopics(where: PunbbTopicWhereInput, orderBy: PunbbTopicOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbTopic]!
  punbbTopicsConnection(where: PunbbTopicWhereInput, orderBy: PunbbTopicOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbTopicConnection!
  punbbUploaded(where: PunbbUploadedWhereUniqueInput!): PunbbUploaded
  punbbUploadeds(where: PunbbUploadedWhereInput, orderBy: PunbbUploadedOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbUploaded]!
  punbbUploadedsConnection(where: PunbbUploadedWhereInput, orderBy: PunbbUploadedOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbUploadedConnection!
  punbbUser(where: PunbbUserWhereUniqueInput!): PunbbUser
  punbbUsers(where: PunbbUserWhereInput, orderBy: PunbbUserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [PunbbUser]!
  punbbUsersConnection(where: PunbbUserWhereInput, orderBy: PunbbUserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PunbbUserConnection!
  node(id: ID!): Node
}

type Subscription {
  punbbBan(where: PunbbBanSubscriptionWhereInput): PunbbBanSubscriptionPayload
  punbbCategory(where: PunbbCategorySubscriptionWhereInput): PunbbCategorySubscriptionPayload
  punbbForum(where: PunbbForumSubscriptionWhereInput): PunbbForumSubscriptionPayload
  punbbOnline(where: PunbbOnlineSubscriptionWhereInput): PunbbOnlineSubscriptionPayload
  punbbPost(where: PunbbPostSubscriptionWhereInput): PunbbPostSubscriptionPayload
  punbbTopic(where: PunbbTopicSubscriptionWhereInput): PunbbTopicSubscriptionPayload
  punbbUploaded(where: PunbbUploadedSubscriptionWhereInput): PunbbUploadedSubscriptionPayload
  punbbUser(where: PunbbUserSubscriptionWhereInput): PunbbUserSubscriptionPayload
}
`