[build]
  base = "server/"
  publish = "public"
  functions = "server/dist/functions"
  command = "yarn build"
  environment = { NODE_ENV = "production", PIGEONHOLE_SERVER = "lambda" }

[build.environment]
  # Fix to ensure the Prisma binary is packaged with the lambda function
  ZISI_VERSION = "0.4.0-9"