[build]
  base = "server/"
  publish = "public"
  functions = "server/dist/functions"
  command = "yarn build"
  environment = { NODE_ENV = "production", PIGEONHOLE_SERVER = "lambda", ZISI_VERSION = "0.4.0-9" }
